WIP watch-contract
fare/gerbil-ethereum pull request #42
Opened 2021-06-09 20:38 UTC by kwannoel

2021-06-12 13:05 UTC, fare commented on simple-apps.ss
> +
I would move this triple logger to a test file.

2021-06-12 13:05 UTC, fare commented on t/70-watch-integrationtest.ss
> +    (test-case "watch-contract: single logs"
Not sure why you need a deque as opposed to a simple list that you pop from on one end, or a list of arrays that you access based on an index then pop off the list, if somehow intra-block indexing is required.

Do you sometimes need to add to the other end while the list is non-empty?

2021-06-14 07:05 UTC, kwannoel commented on t/70-watch-integrationtest.ss
> +    (test-case "watch-contract: single logs"
Wanted to store ordered logs with FIFO property, so we can extract the earliest log from each batch of logs. As such I used a deque which provides those properties.
I assumed lists in gerbil scheme were O(1) cons (push to back of queue), O(n) pop (pop from front of queue).

2021-06-14 11:25 UTC, fare commented
Note to add in a TODO:
If we don't persist the events in the database with the continuation, then we must persist the cursor (block number plus event index within block) and be able to reconstitute the watch state from that.

2021-06-15 19:12 UTC, kwannoel commented
> Note to add in a TODO:
> If we don't persist the events in the database with the continuation, then we must persist the cursor (block number plus event index within block) and be able to reconstitute the watch state from that.

Just implemented in latest commits. Porting over to `glow`.

2021-06-15 19:14 UTC, kwannoel commented on simple-apps.ss
> +
remove extra-line

2021-06-15 19:15 UTC, kwannoel commented on t/70-watch-integrationtest.ss
> +    (test-case "watch-contract: single logs"
We revert to storing an index of the events we have yet to look at in a block, instead of storing all the logs in a `deque`.

2021-06-15 19:16 UTC, kwannoel commented on testing.ss
> +(def (triple-trivial-logger-runtime)
Remove this, it has become obsolete

2021-06-15 19:18 UTC, kwannoel commented on watch.ss
> +                    (values latest-block (1+ next-event)) ; Unprocessed logs in the from-block
```suggestion
                    (values latest-block (1+ next-event)) ; Unprocessed logs in the latest-block
```

2021-06-15 19:19 UTC, kwannoel commented on watch.ss
> +
Docs for how we partition

2021-06-16 13:31 UTC, fare commented on t/70-watch-integrationtest.ss
> +        (def logs '())
Use `:std/misc/list-builder`

2021-06-16 21:22 UTC, zenhack requested changes
Mostly style issues, looks broadly reasonable to me.

2021-06-16 21:22 UTC, zenhack commented on watch.ss
> +        (else #f))
I think we should return `[]` instead of `#f` here (and in the other else)?

2021-06-16 21:22 UTC, zenhack commented on t/70-watch-integrationtest.ss
> +      (def (watch-result->string watch-result) (bytes->string (.@ (.@ watch-result log) data)))
You can combine multiple calls to `.@` into a single one, i.e.`(.@ watch-result log data)` (this shows up in a couple other places too).

2021-06-16 21:22 UTC, zenhack commented on t/70-watch-integrationtest.ss
> +      (def (watch-result->string watch-result) (bytes->string (.@ (.@ watch-result log) data)))
This function is duplicated from above; it should be factored out and shared.

2021-06-16 21:22 UTC, zenhack commented on t/70-watch-integrationtest.ss
> +      (with-list-builder (push-logs! get-logs!)
Is there a reason you didn't use `with-list-builder` in the first test case above?

2021-06-17 18:35 UTC, kwannoel commented on watch.ss
> +        (else #f))
`get-logs-from-blocks/tc` does not return values. It uses `f` as callback.

2021-06-17 18:35 UTC, kwannoel commented on watch.ss
> +        (else #f))
I have updated it anyway to `[]`.

2021-06-17 18:49 UTC, kwannoel commented on t/70-watch-integrationtest.ss
> +      (with-list-builder (push-logs! get-logs!)
Updated to test within the callback. We shouldn't need to construct lists here since we are dealing with a single log.

2021-06-17 21:24 UTC, zenhack approved these changes

2021-06-18 10:19 UTC, kwannoel commented on t/70-watch-integrationtest.ss
> +    (test-case "watch-contract: single logs"
Resolving this, since we no longer return logs in batches, only singly.
We also do not store unprocessed logs in runtime, [although it is marked as a TODO](https://gitlab.com/mukn/glow/-/merge_requests/148/diffs#2080800a3b3a15254802e6bb612a6c84d9b51234_197_194). (we do store an index to indicate which logs are unprocessed in a block).

2021-06-18 10:32 UTC, kwannoel commented
Rewrite commit message to reference the issue.

2021-06-18 10:33 UTC, merged