Add API_Key substitution
fare/gerbil-ethereum pull request #44
Opened 2021-06-15 23:08 UTC by janus

Add API_Key substitution

2021-06-16 13:27 UTC, fare requested changes

2021-06-16 13:27 UTC, fare commented on json-rpc.ss
> +            ((pregexp-match "\\$\\{.+\\}" url) (pregexp-replace "\\$\\{.+\\}" url key))
Wow, you're not even checking the content between the braces!

2021-06-16 13:27 UTC, fare commented on json-rpc.ss
> +  (cond ((string-contains url "infura")
We don't need to check this string-contains, only the ${}

2021-06-16 13:27 UTC, fare commented on json-rpc.ss
> +(def (substitute-key-label-with-key url key: (key #f))
Where is this function called?

It's not named well.

2021-06-29 00:07 UTC, fare commented
Ping. Are you still working on this? Do you have it working on your computer yet?

2021-06-29 00:54 UTC, janus commented
> Ping. Are you still working on this? Do you have it working on your computer yet?

It worked perfectly on my system . I would update with your comments in few hours.

2021-06-30 10:00 UTC, janus commented on json-rpc.ss
> +  (cond ((string-contains url "infura")
Resolved.

2021-06-30 10:00 UTC, janus commented on json-rpc.ss
> +            ((pregexp-match "\\$\\{.+\\}" url) (pregexp-replace "\\$\\{.+\\}" url key))
Resolved

2021-06-30 10:04 UTC, janus commented
I added `infura-api-key-map<-file`. Please check if it is okay and inside the right file.
```(write-file-json (config-path "key.json") foo)
*** ERROR IN clan/temporary-files#make-temporary-file__% -- No such file or directory
(open-file '(path: "/home/emeka/.config/gerbil-application//key.jsontzRR5E.tmp" create: #t))
``` 
I got the above when I use `config-path`. How do I get the folder created?

`url-with-api-key` was rigorously tested on console.

2021-06-30 20:02 UTC, plotnick commented on json-rpc.ss
> +        (else (pregexp-replace "\\$\\{.+\\}" url key))))
Just because a string contains `${INFURA_API_KEY}`, that does not mean that the `\\$\\{.+\\}"` regexp will match it. What about `https://foo.bar/${FOO}/bar/${INFURA_API_KEY}`?

2021-06-30 20:29 UTC, janus commented on json-rpc.ss
> +        (else (pregexp-replace "\\$\\{.+\\}" url key))))
Thanks. Resolved.

2021-06-30 20:33 UTC, fare commented on json-rpc.ss
> +        (else (pregexp-replace "\\$\\{.+\\}" url key))))
No, you're checking something, then you're potentially replacing something else without checking. That's not good.

2021-06-30 20:39 UTC, fare commented on json-rpc.ss
> +        (else (pregexp-replace "\\$\\{.+\\}" url key))))
I think that's the main problem I have with your contributions: you seem to be looking for shortcuts, but these shortcuts end up making the finding of a complete solution longer and harder.

A real solution is complete, with no unhandled cases, no dangling threads, no backdoor, no escapes, that could later be used by enemies, or will just consume the attention and worry space of friends.

Also, communication is difficult and slow. This has been over two weeks since the first commit! And where is this function hooked in the rest of the code? Can you connect on ropsten or rinkeby with that???

2021-06-30 20:59 UTC, janus commented on json-rpc.ss
> +        (else (pregexp-replace "\\$\\{.+\\}" url key))))
> No, you're checking something, then you're potentially replacing something else without checking. That's not good.

I have updated the code already.

2021-06-30 21:00 UTC, janus commented on json-rpc.ss
> +        (else (pregexp-replace "\\$\\{.+\\}" url key))))
> I think that's the main problem I have with your contributions: you seem to be looking for shortcuts, but these shortcuts end up making the finding of a complete solution longer and harder.
> 
> A real solution is complete, with no unhandled cases, no dangling threads, no backdoor, no escapes, that could later be used by enemies, or will just consume the attention and worry space of friends.
> 
> Also, communication is difficult and slow. This has been over two weeks since the first commit! And where is this function hooked in the rest of the code? Can you connect on ropsten or rinkeby with that???

Noted.

2021-06-30 21:17 UTC, janus commented on json-rpc.ss
> +        (else (pregexp-replace "\\$\\{.+\\}" url key))))
> I think that's the main problem I have with your contributions: you seem to be looking for shortcuts, but these shortcuts end up making the finding of a complete solution longer and harder.
> 
> A real solution is complete, with no unhandled cases, no dangling threads, no backdoor, no escapes, that could later be used by enemies, or will just consume the attention and worry space of friends.
> 
> Also, communication is difficult and slow. This has been over two weeks since the first commit! And where is this function hooked in the rest of the code? Can you connect on ropsten or rinkeby with that???

It is hooked up here:
```
(def (ethereum-url<-config config infura-api-file: (infura-api-file #f))
  (let (url (car (.@ config rpc)))
    (if infura-api-file 
      (url-with-api-key url key: (hash-get (infura-api-key-map<-file infura-api-file) 'key))
      url)))
```

2021-06-30 21:25 UTC, fare commented on json-rpc.ss
> +        (else (pregexp-replace "\\$\\{.+\\}" url key))))
OK, I see, better. That wasn't there yesterday.

Where is the format of that file documented? I can guess by reading the code, but surely that's not how users are supposed to figure it out. Can you document that in the README as well as in comments for the relevant functions?

2021-07-01 08:33 UTC, janus commented
> Add an example with a random key (invalid, but with the correct format).

Done.

2021-07-01 08:34 UTC, janus commented
> Same here.

Done.

2021-07-01 19:59 UTC, fare requested changes

2021-07-01 23:09 UTC, janus commented on json-rpc.ss
> +;; File is expected to be already created and inside this folder, ~/.config/gerbil-application/
> shouldn't it be ~/.config/glow/ ?

```
> (import :clan/path-config)
> (config-path "key.json")
"~/.config/gerbil-application/key.json"
```

2021-07-01 23:12 UTC, janus commented on json-rpc.ss
> +;; File is expected to be already created and inside this folder, ~/.config/gerbil-application/
> And where is an example of that file?
> 
> Actually, it might be better to name the file something like "url_substitutions.json" and have it contain a value `{"INFURA_API_KEY": "0123456789abcdef0123456789abcdef"}`, and then make the substitution more generic.
> And to also accept environment variables for allowed substitutions.

What is the essence of having a specific name for the file?

2021-07-01 23:43 UTC, janus commented on json-rpc.ss
> +;; File is expected to be already created and inside this folder, ~/.config/gerbil-application/
Updated .

2021-07-02 03:43 UTC, fare commented on network-config.ss
> +(def (infura-api-key-map<-file infura-api-filename)
Did you test that? It looks like there is double reading of json. `read-file-json` should do everything for you.

Also, it should be using strings rather than symbols as keys.

2021-07-02 03:43 UTC, fare commented on json-rpc.ss
> +;; File(json) name `url_substitutions.json`
What's the meaning of this file here??? You don't use it below!

And if it's going to be generic, maybe for more than infura, maybe for more than urls, maybe it should be called user_variables.json or access_tokens.json or something. Or maybe it should be stored in the secret database that @plotnick is developing?

2021-07-02 05:32 UTC, fare commented on json-rpc.ss
> +;; File is expected to be already created and inside this folder, ~/.config/gerbil-application/
Having a specific name is important, because we need to document where it goes so the users can use it, otherwise it's useless.

And gerbil-ethereum's test and run scripts should probably initialize the application-name to "glow" so the very same file can be used... I just pushed a commit to that effect (you might want to rebase).

2021-07-02 05:32 UTC, fare commented on json-rpc.ss
>  (def (ethereum-url<-config config infura-api-file: (infura-api-file #f))
Let's make the mechanism NOT infura-specific, and the variable names not infura specific. Only the configuration file should have an infura-specific content, as well as the relevant network definitions.

2021-07-02 09:08 UTC, janus commented on network-config.ss
> +(def (infura-api-key-map<-file infura-api-filename)
> Did you test that? It looks like there is double reading of json. `read-file-json` should do everything for you.
> 
> Also, it should be using strings rather than symbols as keys.

```(read-file-json (config-path "infura_api_key.json")) 
"{\"key\": \"0292948488deedbeaf\"}"
```
```
(def kmap (infura-api-key-map<-file "infura_api_key.json"))
> (hash-get kmap 'key)
"0292948488deedbeaf"
```

2021-07-02 09:46 UTC, janus commented on json-rpc.ss
>  (def (ethereum-url<-config config infura-api-file: (infura-api-file #f))
Done.

2021-07-02 09:47 UTC, janus commented
Updated.

2021-07-02 18:02 UTC, plotnick commented
I do not think we should merge this as-is. In particular, the heart of the patch, the `${KEY}` substitution pass, is not robust or general enough. I think we should have something more like:

+ A character-at-a-time scanner that looks for `${KEY}` patterns in a string, and returns a list of `(key start end)` structs. This routine should not mention the words "API" or "URL"; its job is so low level that it has no knowledge of what kind of keys it's looking for or in what kind of string. It should not need to use regular expressions. It must have unit tests.
+ A substitution routine that takes a string (not treating it as or calling it a URL), calls the scanner, and substitutes values for keys at the specified positions. It must accept a list of allowed keys, and you must decide whether keys that are present but not in the allowed list raise an error, are silently ignored, etc. You must also decide what to do with missing or empty values. This should be a "batch" operation that substitutes all of the values at once. If any substitution fails, they should all fail, and if you have a file that you're loading values from, it should only be opened and read once. I would be fine with just environment variables for now, though. This must also have unit tests.
+ A routine that takes a URL and a list of allowed keys, and calls the substitution routine just on the path component (I think; we don't want to substitute keys into hostnames, right?), and returns an new URL with the substituted values.
+ A clear way that the above can be or is hooked up to the rest of the system. For this particular use case, it should use the list of allowed keys `'("INFURA_API_KEY")`. This must include an integration test that shows it successfully talking to the Infura API.

We would like to be able to trivially use this facility to substitute keys or variables other than Infura, and it's not really clear to me that this is even Ethereum specific, and so should arguably be done somewhere entirely different, like `glow` or even `gerbil-utils`. I do not have strong feelings on that right now, and it's already here; we can move it if we need to once it works.

Feel free to suggest or implement variations, alterations, etc. to the above as necessary. But I would like to see something along these lines — including, especially _tests_ — before this is merged.

2021-07-02 20:58 UTC, janus commented
>     * A clear way that the above can be or is hooked up to the rest of the system. 

It is already hooked up to the rest of the system. `init-ethereum-connection` starts every network, and url is not currently limited to Infura, url could be for PET or Cardano. `init-ethereum-connection` is called when Glow tries to connect to a network. `ethereum-url<-config` calls the substitution function. 

```
(def (init-ethereum-connection name poll: poll)
  (def network (ensure-ethereum-network name))
  (def config (ethereum-network-config network))
  (def url (ethereum-url<-config config api-key-file: api-key-file))
```

*) PET and Cardano do not need string substitution, however future end nodes might need some.
*) Unit test and integration test would added once the code is okay for use.
@fare  Where would you want the `character-at-a-time scanner` to be?  I am thinking that it should be inside gerbil-utils.

2021-07-02 22:08 UTC, plotnick commented
> *) Unit test and integration test would be added once the code is okay for use.

Unit tests and integration tests must be added before this is merged. The code is not "okay for use" until tests show that it is.

> Where would you want the `character-at-a-time scanner` to be? I am thinking that it should be inside gerbil-utils.

I would prefer to keep it here for now to avoid complicating factors. It could be in a new file, or not.

2021-07-02 22:21 UTC, plotnick commented
Looking at this again, maybe two passes is overkill, and could lead to tricky indexing. Feel free to do the substitutions in one pass through the string, but it should have rougly the behavior described above.

2021-07-03 00:16 UTC, janus commented
Unit test morrow

2021-07-04 05:01 UTC, fare commented on json-rpc.ss
> +(def (get-env-variables tokens)
1. For security reasons, we probably want a shortlist of allowed variables.
2. We probably want to lookup a configuration file when the variable is not in the environment.
3. Where is this function used?

2021-07-04 05:04 UTC, fare commented on json-rpc.ss
> +        (let (char (string-ref str index))
I think you should be using the `string-index` function from `srfi/13` for finding the next `$` character, etc.

2021-07-05 11:30 UTC, janus commented
@plotnick  What is the security reason for Allowed list(White list)? What is its benefit?

To Do:
+) More unit tests
+) Integration test (Glow)

2021-07-05 11:31 UTC, janus commented on json-rpc.ss
> +        (let (char (string-ref str index))
Thanks. I would try it out.

2021-07-05 11:33 UTC, janus commented on json-rpc.ss
> +(def (get-env-variables tokens)
`For security reasons, we probably want a shortlist of allowed variables.` What is the benefit?
`We probably want to lookup a configuration file when the variable is not in the environment.` Done`
`Where is this function used?` It is in the latest update.

2021-07-05 16:16 UTC, plotnick commented
> What is the security reason for Allowed list(White list)? What is its benefit?

Since (some of) the things we'll be substituting are bearer tokens, i.e., secret keys, we must be careful where and how we substitute them. For instance, a malicious party could convince someone to copy-and-paste a URL containing a reference to `${SOME_SECRET}`, which could then, when they make a connection, unintentionally leak the actual secret. So I think that each network-specific connection routine that requires a specific set of secrets should specify exactly and only those keys; e.g., connecting to an Ethereum network with Infura should substitute (only) the `${INFURA_API_KEY}`, but a connection to some other network definitely should not.

2021-07-06 03:21 UTC, fare requested changes
I was thinking that the list of variables should be more like context/type dependent, i.e. the connection variables such as the INFURA_API_KEY are only available during the substitution for the connection URL, which should not be edited often, especially not by lay users.

But yes, if lay users are going to type such connection URLs, it would be nice to offer extra protections.

In any case, the general idea is that allowing substitution of arbitrary variables in arbitrary contexts can leak sensitive data to an enemy. A comment to that effect should probably accompany the function that computes substitutions:
```
;; Be careful that no potentially adversary-provided string should be used as the template for substitutions
;; involving potentially private variables. The default set of allowed variables should be empty, and
;; every context that calls the substitution function should be wary to provide a minimal set of allowed variables.
```

2021-07-06 03:21 UTC, fare commented on json-rpc.ss
> +;; File contain `{"END_NODE_API_KEY": "0123456789abcdef0123456789abcdef"}` . Remember to use a valid key
The example should probably use a valid key string INFURA_API_KEY instead of END_NODE_API_KEY.

2021-07-06 03:21 UTC, fare commented on json-rpc.ss
> +(def (get-env-values tokens api-key-file: (api-key-file #f))
It's confusing that you're shadowing a global variable.

2021-07-06 03:21 UTC, fare commented on json-rpc.ss
> +(def allowed-map (hash ("infura" ["INFURA_API_KEY"])))
Shouldn't the map go the other direction? And be a hash-set, actually. A global hash-set of variable names should probably be fine.

2021-07-06 03:21 UTC, fare commented on json-rpc.ss
> +;; File contain `{"END_NODE_API_KEY": "0123456789abcdef0123456789abcdef"}` . Remember to use a valid key
Use a valid key string "INFURA_API_KEY" instead of the non-existent "END_NODE_API_KEY".

2021-07-06 03:21 UTC, fare commented on json-rpc.ss
> +      (url-with-api-key url key: (or (getenv "END_NODE_API_KEY" #f) (hash-get (api-key-map<-file api-key-file) 'END_NODE_API_KEY)))
What's this END_NODE_API_KEY thing????????

2021-07-06 03:21 UTC, fare commented on t/json-rpc-test.ss
> +      (setenv "INFURA_API_KEY" "899999990000")
the format looks like 32 hex digits, not 12 decimal digits.

2021-07-09 10:37 UTC, janus commented on t/json-rpc-test.ss
> +      (setenv "INFURA_API_KEY" "899999990000")
I don't want to reveal much to the user.

2021-07-09 10:37 UTC, janus commented on json-rpc.ss
> +      (url-with-api-key url key: (or (getenv "END_NODE_API_KEY" #f) (hash-get (api-key-map<-file api-key-file) 'END_NODE_API_KEY)))
Thanks already removed

2021-07-09 10:38 UTC, janus commented on json-rpc.ss
> +;; File contain `{"END_NODE_API_KEY": "0123456789abcdef0123456789abcdef"}` . Remember to use a valid key
Okay

2021-07-09 10:41 UTC, janus commented on json-rpc.ss
> +(def allowed-map (hash ("infura" ["INFURA_API_KEY"])))
Is `hash-set` a function? I have searched for it already.

2021-07-09 10:41 UTC, janus commented on json-rpc.ss
> +(def (get-env-values tokens api-key-file: (api-key-file #f))
Refactor. Thanks.

2021-07-09 17:13 UTC, plotnick requested changes

2021-07-09 17:13 UTC, plotnick commented on t/json-rpc-test.ss
> +      (setenv "INFURA_API_KEY" "899999990000")
> I don't want to reveal much to the user.

Eh? I get that you shouldn't embed your actual key, but surely you could match the format with, say, 32 copies of one hex digit.

2021-07-09 17:13 UTC, plotnick commented on json-rpc.ss
> +(def api-key-file "url_substitutions.json")
I still think this file is unnecessary, and that it would simplify both our mental model and the code if we only supported environment variables for now. Is there a specific use case that requires this file?

2021-07-09 17:13 UTC, plotnick commented on json-rpc.ss
> +        vals)))
I don't undestand this code. I think it means that if any environment lookup fails, then you look up everything from the file, but wouldn't that replace values that were already got from the environment? Another argument for eliminating that file.

2021-07-10 23:34 UTC, janus commented on t/json-rpc-test.ss
> +      (setenv "INFURA_API_KEY" "899999990000")
Okay. I would update to 32.

2021-07-10 23:35 UTC, janus commented on json-rpc.ss
> +(def (parse-url url)
Update.

2021-07-10 23:36 UTC, janus commented on json-rpc.ss
> +(def (create-list-of-substring-with-string-separation str tokens)
Updated with `with-output-to-string`.

2021-07-10 23:36 UTC, janus commented on json-rpc.ss
> +      (error "Generated variable list not allowed " tokens)))
It would be added soon.

2021-07-10 23:36 UTC, janus commented on json-rpc.ss
> +          (begin
Done.

2021-07-10 23:37 UTC, janus commented on t/json-rpc-test.ss
> +      (def token (make-token 90 "Hoop" 120))
Done.

2021-07-10 23:38 UTC, janus commented on json-rpc.ss
> +(def api-key-file "url_substitutions.json")
Done.

2021-07-10 23:38 UTC, janus commented on json-rpc.ss
> +        vals)))
Done.

2021-07-11 02:24 UTC, fare commented on README.md
> +  "INFURA_API_KEY" "899999990000". Remember to change API key to your own key.
Please only ever use but well-formed values as example, which means a 32-hex char string for the value of INFURA_API_KEY.

2021-07-11 02:24 UTC, fare commented on json-rpc.ss
> +(def allowed-list [["INFURA_API_KEY"]])
why is this a list of lists and not just a list or a hashset? You may use `hashset<-list` from `:clan/hash`.

2021-07-11 02:24 UTC, fare commented on json-rpc.ss
> +                  (with-output-to-string result (cut display (substring path offset (string-length path))))
This excessive use of `with-output-to-string` sucks. There should be only one call to it, wrapping everything.

2021-07-11 02:24 UTC, fare commented on json-rpc.ss
> +(def (parse-uri uri prefix)
THERE SHOULD NOT BE A PARSE-URI FUNCTION HERE. ARE YOU CRAZY??????????????

2021-07-11 12:50 UTC, janus commented on json-rpc.ss
> +(def (parse-uri uri prefix)
@fare  What is wrong with `parse-uri`? And why are you against it?

2021-07-11 12:51 UTC, janus commented on json-rpc.ss
> +(def allowed-list [["INFURA_API_KEY"]])
I would go with list to avoid making simple thing complex

2021-07-11 12:51 UTC, janus commented on json-rpc.ss
> +                  (with-output-to-string result (cut display (substring path offset (string-length path))))
Hmmm, I have not figured out how this would work.

2021-07-11 12:52 UTC, janus commented on README.md
> +  "INFURA_API_KEY" "899999990000". Remember to change API key to your own key.
Noted

2021-07-11 15:40 UTC, fare commented on README.md
> +  "INFURA_API_KEY" "899999990000". Remember to change API key to your own key.
I even provided an example in one of the comments above!

2021-07-11 15:43 UTC, fare commented on json-rpc.ss
> +(def (parse-uri uri prefix)
1. The entire point of this exercise is to have a SIMPLE STRING INTERPOLATION model for configuring connection URLs. Now you're requiring the user to understand the parsing of a URL and the interplay between two parsers??? That's C R A Z Y.

2. ***IF*** there were a need for parsing URIs, that's not at all where it belongs. Besides, there are already such parsers in Gerbil, or should be.

2021-07-11 15:44 UTC, fare commented
This entire issue was suppose to be a 3-day job at most, implementing a simple string substitution mechanism. It has been stretching out for one month going in plenty of absurd directions. It would have been better and faster to do it myself than to ask you to do it.

2021-07-11 15:50 UTC, janus commented on json-rpc.ss
> +(def (parse-uri uri prefix)
I am following @plotnick directive here. He said that `url-substitution` function argument should be a path only.  And I was told not to use regex. That's what led to `parse-url`.

2021-07-11 15:50 UTC, janus commented
> This entire issue was suppose to be a 3-day job at most, implementing a simple string substitution mechanism. It has been stretching out for one month going in plenty of absurd directions. It would have been better and faster to do it myself than to ask you to do it.

Noted.

2021-07-11 15:52 UTC, janus commented on README.md
> +  "INFURA_API_KEY" "899999990000". Remember to change API key to your own key.
This is already done in my latest update.

2021-07-11 17:11 UTC, plotnick commented on json-rpc.ss
> +(def (parse-uri uri prefix)
That's correct, this was me. I pointed out that we had to parse the URL in a minimal way so that we don't interpolate into the host portion. I agree that this is not the ideal location, or its final form, but I couldn't find anything else and didn't want to complicate things further by dealing with multiple locations for right now. We can refactor as needed later.

2021-07-11 17:47 UTC, fare commented
Here's the substitution function I wanted:
```
;; Given a string and a function that interpolates strings inside ${xxx} into strings,
;; replace the ${strings} with the function results, and any $$ with single $.
;; String <- String (Fun String <- String)
(def (string-interpolate s f)
  (def l (string-length s))
  (def (c i) (and (> l i) (string-ref s i)))
  (call-with-output-string
    (lambda (o)
      (let loop ((i 0))
        (def j (string-index s #\$ i))
        (if j
          (begin
            (when (> j i) (write-string (substring s i j) o))
            (let (ch (c (1+ j)))
              (case ch
                ((#\{)
                 (let (k (string-index s #\} (+ j 2)))
                   (unless k
                     (error "Invalid interpolation" s j))
                   (write-string (f (substring s (+ j 2) k)) o)
                   (loop (1+ k))))
                ((#\$) (write-char ch o) (loop (+ j 2)))
                (else (write-char #\$ o) (loop (+ j 1))))))
          (write-string (substring s i l) o))))))
```

2021-07-11 19:55 UTC, fare commented
OK, I just pushed 11ab3fb493cd46b5b4f7ba1303c574893b380233 in which I use the above `string-interpolate` function to achieve the desired effect in 15 lines of code added or modified.

It doesn't include the configuration file, but @plotnick above convinced me that this wasn't necessary, at least for now.

2021-07-11 19:57 UTC, fare commented
It took all of 4 hours including testing, having lunch, and playing with my kids.

Closing the issue.

2021-07-11 19:57 UTC, closed without merging

2021-07-11 20:00 UTC, fare commented
(Also in those 4 hours, improving the output of the `list-evm-networks` subcommand.)