Implement EVM type descriptors
fare/gerbil-ethereum pull request #46
Opened 2021-06-25 21:08 UTC by kwannoel

See `types.ss`.

Part of https://gitlab.com/mukn/glow/-/issues/80.

2021-06-25 21:09 UTC, kwannoel commented on t/types-integrationtest.ss
> +(export #t)
Skip this file for now. This is copy pasted from other integration tests. To be modified.

2021-07-01 20:39 UTC, kwannoel commented on types.ss
> +
Remove

2021-07-01 21:05 UTC, kwannoel commented on assembly.ss
> +;; Stack: | value | ... |
remove

2021-07-02 05:36 UTC, fare commented on assembly.ss
> +;; 0x ff ff ff    ...    ff aa 11
Unclear what this is being represented. A 33-byte integer? Some record with a 31-byte integer field, followed by two 1-byte fields?

2021-07-05 15:06 UTC, kwannoel commented on assembly.ss
> +  :std/format :std/misc/bytes :std/misc/list :std/misc/number
Remove import

2021-07-05 15:06 UTC, kwannoel commented on evm-runtime.ss
> +;; We have to PUSH later bytes first,
Add NOTE:

2021-07-05 15:07 UTC, kwannoel commented on evm-runtime.ss
> +;; TODO test when size = 0
Remove

2021-07-05 15:07 UTC, kwannoel commented on t/80-evm-eval-integrationtest.ss
> +      ;; TODO Integrate these with existing EVM types,
Remove

2021-07-05 16:45 UTC, kwannoel commented on assembly.ss
> +;; 0x ff ff ff    ...    ff aa 11
Updated here: https://github.com/fare/gerbil-ethereum/pull/46/files#diff-61b54f933d2406971aa705cb01aaeb6d4edae919accf5f1009c04e3c082a8c40R672

2021-07-05 16:54 UTC, kwannoel commented on t/80-evm-eval-integrationtest.ss
> +    (test-case "EVM-type/&mem<-stack<- size = 1"
Move these out into their own integration tests.

2021-07-05 16:59 UTC, kwannoel commented on t/type-descriptors-test.ss
> +  :gerbil/gambit/bytes
Purge unnecessary imports

2021-07-05 18:06 UTC, kwannoel commented on evm-runtime.ss
> +;; E.g. (offsets-and-sizes<-size 65) -> [[0 . 32] [32 . 32] [64 . 1]]
Not pair, list of lists.

2021-07-05 18:06 UTC, kwannoel commented on evm-runtime.ss
> +;; stack output: value/0 value/1 ... value/n
bytes/0 bytes/1 ...

2021-07-05 18:08 UTC, kwannoel commented on type-descriptors.ss
> +;; TODO Separate types used for existing ABI and EVM types??
Tracked in issue under integrating with EVM types, can remove.

2021-07-05 18:08 UTC, kwannoel commented on type-descriptors.ss
> +;; TODO right to left arrows naming conventions
resolved

2021-07-05 18:09 UTC, kwannoel commented on type-descriptors.ss
> +;; TODO abstract stack->mem etc..
resolved

2021-07-05 18:27 UTC, kwannoel commented
Rebased and cleaned up commits.

2021-07-05 18:29 UTC, kwannoel commented on type-descriptors.ss
> +;; We are shadowing existing types. Should we monkey-patch them instead? Let's hope not.
remove copy pasted stuff

2021-07-05 18:29 UTC, kwannoel commented on type-descriptors.ss
> +  (for-syntax :gerbil/gambit/exact :std/iter :std/stxutil :clan/syntax)
cleanup imports

2021-07-12 17:02 UTC, fare approved these changes

2021-07-12 17:02 UTC, fare commented on evm-instructions.ss
> +    ([] (&begin POP 0)
Either unit types should be statically optimized away, or should dynamically have some marker, but whatever the convention is, we must make it consistent.

2021-07-12 17:02 UTC, fare commented on t/100-evm-instructions-integrationtest.ss
> +                            )))
parens

2021-07-12 17:02 UTC, fare commented on t/80-evm-eval-integrationtest.ss
> +                result-in-memory?: #t))
parens

2021-07-12 17:02 UTC, fare commented on t/evm-instructions-test.ss
> +                    ])
parens

2021-07-12 18:42 UTC, zenhack requested changes
Left some comments in-line

2021-07-12 18:42 UTC, zenhack commented on evm-instructions.ss
> +  (assert! (<= 1 size) (format "size: ~d not in range: [1,∞]")) ; TODO: provide a concrete upper bound
Whatever we decide to do re: validating the size of inputs, we should probably factor it out into a shared function; you have the same assert (with the same TODO) elsewhere.

2021-07-12 18:42 UTC, zenhack commented on evm-instructions.ss
> +;; For example, given the value: 0x00ff,
I agree this is confusing; I would expect this to live in one slot on the stack, since it fits in 2 bytes and the word size is 32 bytes.

2021-07-12 18:42 UTC, zenhack commented on evm-instructions.ss
> +;; Given relative-offset and size,
Should specify a formal signature here. It isn't immediately obvious how the arguments are passed in.

2021-07-12 18:42 UTC, zenhack commented on evm-instructions.ss
> +    ([] (&begin POP 0)
Agree; my feeling is that `(&mload/any-size 0)` should not push anything onto the stack.

2021-07-12 23:13 UTC, fare commented on evm-instructions.ss
> +  (def end (min len (+ start 32)))
We do care about supporting data structures sizes that are not multiple of 32, because storage is so expensive that if we can save one word of SSTORE it will save 5000 GAS which at current prices is about 15 cents. Per store, per invocation. Even one saved reading would be 2100 GAS, or over 6 cents.

I believe the current `&push` assumes left-padding. We could keep that. Or we could support the Solidity ABI of left-padding for numbers, right-padding for bytes. They are the two options that make sense. Always left-pad seems cheaper both in human time and in EVM runtime.

2021-07-19 06:25 UTC, kwannoel commented on evm-instructions.ss
> +  )
Thanks for pointing this out.

2021-07-19 06:29 UTC, kwannoel commented on assembly.ss
> +;; 0x ff ff ff    ...    ff aa 11
Follow up thread: https://github.com/fare/gerbil-ethereum/pull/46#discussion_r667566744

2021-07-19 06:39 UTC, kwannoel commented on evm-instructions.ss
> +  (def n-words (truncate (/ size word-size)))
Thanks for these.

Where can I find `floor/` / `floor-quotient` in documentation?
It does not appear in usual references:
- https://schemers.org/Documents/Standards/R5RS/HTML/
- https://www.iro.umontreal.ca/~gambit/doc/gambit.html#General-index
- https://srfi.schemers.org/?q=floor

2021-07-19 06:54 UTC, kwannoel commented on evm-instructions.ss
> +  (def n-words (truncate (/ size word-size)))
Found it in [r7rs](https://small.r7rs.org/attachment/r7rs.pdf).

2021-07-19 07:34 UTC, kwannoel commented on evm-instructions.ss
> +;; stack output: part0 part1 ... partn
To clarify: 
`Thunk` refers to code, which when evaluated, will return the expected value, i.e. `part0 ... partn`.

2021-07-19 08:08 UTC, kwannoel commented on evm-instructions.ss
> +;; Given relative-offset and size,
Included here: https://github.com/fare/gerbil-ethereum/pull/46/files#diff-6c56dd17a26fa6ddfd679ad2e9545670edacc0322c7e5f2a94199a7385c20fabR86

2021-07-19 08:11 UTC, kwannoel commented on evm-instructions.ss
> +    ([] (&begin POP 0)
Was following convention from our `assembly.ss` code:
```
(def (&mload n-bytes)
  (assert! (and (exact-integer? n-bytes) (<= 0 n-bytes 32)) "Bad length for &mload")
  (cond
   ((zero? n-bytes) (&begin POP 0)) ;; [3B, 5G]
  ...
```

2021-07-19 08:13 UTC, kwannoel commented on evm-instructions.ss
> +    ([] (&begin POP 0)
Will follow @zenhack 's suggestion and just `POP` the `offset`.

2021-07-19 08:15 UTC, kwannoel commented on evm-instructions.ss
> +;; stack output: part0 part1 ... partn
Updated with signature.

2021-07-19 08:43 UTC, kwannoel commented on evm-instructions.ss
> +;; For example, given the value: 0x00ff,
I think my wording was ambiguous.
Instead of the first slot on EVM stack as `0x00` and second slot as `0xff`,
I meant the **first byte** on EVM stack should be `0x00` and **second byte** should be `0xff`.
Each element of the array will not occupy an entire EVM slot on its own.

Have reworded the example.

2021-07-19 09:23 UTC, kwannoel commented on evm-instructions.ss
> +  (assert! (<= 1 len) (format "size: ~d not in range: [1,∞]")) ; TODO: provide a concrete upper bound
> We could also assert that start + len <= length(bytes), rather than just no-oping. Generally better to err on the side of catching mistakes sooner rather than later. This also conveniently obviates picking a specific upper bound.

`start` is updated to point to the start of the section of the array we have not generated thunks for.
`len` is a constant which stores the total number of bytes, rather than the length of the current section.

For instance given:
```
start = 0, length(bytes) = 64
```

During the first iteration, we will load the first 32 bytes i.e. 0...31(inclusive). 

In the second iteration we will have:
```
start = 32, len = 64 ;; See here that len is unchanged.
```

In that case `start + len = 96 > len = 64`.

I have renamed `len` to `total-bytes` to make this distinction clear.
Added in assertions to provide similar guarantees.
```
  (assert! (< start total-bytes))
  (assert! (<= end total-bytes))
  (when (< start end)
    ...
```

2021-07-19 09:29 UTC, kwannoel commented on evm-instructions.ss
> +;; stack input: -
`&push/any-size` uses the existing `&push-bytes` instruction provided in `assembly.ss`.
Hence this follows our current left-pad convention.

2021-07-19 09:43 UTC, kwannoel commented on evm-instructions.ss
> +;; stack input: -
> Re: left vs. right padding, another alternative would be to just throw an error if the input is not a multiple of the word size, forcing the caller to make the decision. I don't have a strong opinion here.
> 
> This could also use some comments describing the rest of the contract for the (scheme) function as well as just a high level "what is this for," rather than just the stack signature of the generated code.

Updated.

2021-07-19 10:03 UTC, kwannoel commented on evm-instructions.ss
> +  (def end (min len (+ start 32)))
> Let's define the magic number 32 as a constant somewhere.

Updated.

2021-07-19 10:04 UTC, kwannoel commented on evm-instructions.ss
> +  (def end (min len (+ start 32)))
> We do care about supporting data structures sizes that are not multiple of 32, because storage is so expensive that if we can save one word of SSTORE it will save 5000 GAS which at current prices is about 15 cents. Per store, per invocation. Even one saved reading would be 2100 GAS, or over 6 cents.
> 
> I believe the current `&push` assumes left-padding. We could keep that. Or we could support the Solidity ABI of left-padding for numbers, right-padding for bytes. They are the two options that make sense. Always left-pad seems cheaper both in human time and in EVM runtime.

Yes that is correct. Approach taken is to left-pad, via `&push` /  `&push-bytes`.

2021-07-19 18:48 UTC, zenhack commented on evm-instructions.ss
> +;; For example, given an array of two bytes: 0x00ff:
This is still confusing to me. Things that would I think make this clearer:

- Using `0x00ff` as notation for an array of bytes is weird, since it looks like a single value (which leaves open the question of endianness. You state big-endian above, but it makes it hard to follow).; I would maybe suggest using gerbil notation for sequences of bytes, i.e. `#u8(#x00 #xff)`, to make this less ambiguous.
- Talking about "bytes" on the stack is confusing; the operand stack does not contain bytes, it contains 32-byte values, whose endianness is unspecified. Instead of describing the operand stack as if it contained bytes, I would specify what the value on the top of the stack is after this push -- which if I'm reading this correctly would be `0x00ff000000000000000000000000000000000000000000000000000000000000`

2021-07-20 13:10 UTC, kwannoel commented on evm-instructions.ss
> +;; stack input: -
From discussion with @zenhack on discord:
> The stack is still defined in 32-byte chunks, so that leaves open the question of what the other 31 bytes in that last word are after the load. Left padding means you have a bunch of zeros in the most-significant bytes, right padding means you have them in the least significant bytes. It's not possible to have a non-integer number of words on the stack. I agree padding is unnecessary and undesirable in memory.

I have added tests to verify left-padding occurs.

2021-07-20 13:16 UTC, kwannoel commented on evm-instructions.ss
> +;; For example, given an array of two bytes: 0x00ff:
I think I was confused regarding padding.
It should be left padded, so we should expect this instead:
```
#x00000000000000000000000000000000000000000000000000000000000011ff
```

I have added testcases in `t/100-evm-instructions-integrationtest.ss` to give a concrete representation of what is expected:
```
    (test-case "EVM-type: &mstore/free/any-size, size = 1, left-padded to EVM-Word size"
      (evm-test [] (&begin
                    &init-brk
                    (&push/any-size #u8(1))    ; stack: 1
                    (&mstore/free/any-size 32)
                    &store-brk
                    )
                [[Bytes32 . #u8(0 0 0 0  0 0 0 0  0 0 0 0  0 0 0 0
                                0 0 0 0  0 0 0 0  0 0 0 0  0 0 0 1
                                )]
                 [UInt256 . 64]]
                result-in-memory?: #t
                result-start: #x20))

    (test-case "EVM-type: &mstore/free/any-size, size = 4, left-padded to EVM-Word size"
      (evm-test [] (&begin
                    &init-brk
                    (&push/any-size #u8(1 2 3 4)) ; stack: 1 2 3 4
                    (&mstore/free/any-size 32)
                    &store-brk
                    )
                [[Bytes32 . #u8(0 0 0 0  0 0 0 0  0 0 0 0  0 0 0 0
                                0 0 0 0  0 0 0 0  0 0 0 0  1 2 3 4
                                )]
                 [UInt256 . 64]]
                result-in-memory?: #t
                result-start: #x20))
```

2021-07-20 13:17 UTC, kwannoel commented on evm-instructions.ss
> +;; For example, given an array of two bytes: 0x00ff:
Updated the examples.

2021-07-20 13:23 UTC, kwannoel commented on t/100-evm-instructions-integrationtest.ss
> +
See this section for padding tests @zenhack.

2021-07-20 18:20 UTC, zenhack approved these changes
LGTM

2021-07-21 03:37 UTC, kwannoel commented on evm-instructions.ss
> +  (def end (min len (+ start 32)))
By default `PUSH` instructions left-pad to evm-word length.

2021-07-21 03:37 UTC, kwannoel commented on evm-instructions.ss
> +;; For example, given the value: 0x00ff,
See comment: https://github.com/fare/gerbil-ethereum/pull/46#discussion_r673112186, 
for follow-up discussion.

2021-07-21 03:43 UTC, kwannoel commented
Rebasing and cleaning up commits (no changes to code).

2021-07-21 03:50 UTC, merged